GPU offload for wave propagation kernel
ecmwf-ifs/ecwam pull request #17
Opened 2024-05-06 09:00 UTC by awnawab

This is the last of the three PRS needed to add GPU acceleration to the wave model timestep.

The work included herein is entirely that of @fdisante and his colleagues at CINECA.

GPU optimised code for the source term integration scheme is generated by Loki at build time. This was possible to do because that kernel follows the single column computation pattern used throughout the IFS, and for which we have Loki transformation recipes.

The wave propagation kernel however has very different and bespoke memory access patterns, for which we do not have Loki recipes. Moreover, the wave propagation kernel is not expected to see as frequent scientific development as the source term integration scheme, so there is also less of a justification to develop Loki recipes for it.

That's why for the wave propagation kernel we have opted for a manual GPU port. This is just OpenACC for now, but OpenMP offload support will also be added at a later date. If we feel the need in the future that the wave propagation kernel would also benefit from auto-generation of GPU optimised code at build-time, then we can develop Loki recipes for that too.

Finally, all the changes herein have been tested in coupled IFS+nemo runs and are confirmed bit-identical.

2024-05-06 09:03 UTC, awnawab commented
Hi @jrbidlot and @jkousal32. Could you also please review the PR? Thanks!

2024-05-06 13:06 UTC, reuterbal reviewed
Looks very good to me!

2024-05-06 14:20 UTC, wdeconinck reviewed
Great development! Thanks all involved!
I have a few minor suggestions, see below.

2024-05-06 14:20 UTC, wdeconinck commented on CMakeLists.txt
> +                    DESCRIPTION "Enable CUDA-aware MPI" )
I would make this instead:
```cmake
ecbuild_add_option( FEATURE GPU_AWARE_MPI
                    DEFAULT OFF
                    DESCRIPTION "Enable GPU-aware MPI"
                    CONDITION HAVE_ACC AND HAVE_MPI )
```
As indeed it relies on OpenACC, and MPI is already a feature above.

2024-05-06 14:20 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +if( HAVE_MPI )
```suggestion
if( HAVE_GPU_AWARE_MPI )
```

2024-05-06 14:20 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +  set( MPI_Fortran_LIBRARIES ${MPI_SERIAL_LIBRARIES} )
```suggestion
```
because we guard MPI calls with #ifdef WITH_GPU_AWARE_MPI

2024-05-06 14:20 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> -      set( MPI_Fortran_LIBRARIES ${MPI_SERIAL_LIBRARIES} )
I would leave these lines in.

So now we will only explicitly link with MPI either when HAVE_GPU_AWARE_MPI or HAVE_UNWAM

2024-05-07 14:58 UTC, jrbidlot requested changes
I had a look at the changes. Not being familiar with opennACC, it is hard for me to comment whether adding these directives was done right. I did look however at propags2 and how it s called and mention that we might want to start from 49R1 version or be aware of changes that have been made in 49R1 that might clash with these changes

2024-05-07 14:58 UTC, jrbidlot commented on src/ecwam/propags2.F90
> +              IF (LLWKPMN(K,M,-1).AND.(.NOT.LLWKPMN(K,M,1))) THEN
OK, the 48R1 made use of LLWKPMN to avoid doing some multiplication and a sum
In 49R1 I have remove that bit to always to the calculation even if it mean mutiplication by 0
It was more efficient on atos.
Now, the code modifications if the different if's are not nice.
Can you look at 49R1 and do the implementation from there.

I also note that it was decided to revert what had been done a while ago by introducing the FJ1 to FJ5 arrays for efficiency reason (note that I did not do that bit). is it necessary for the GPU porting. Also what about the non GPU performance. This is one of the most expensive part of the code, especially at high resolution. We could only accept changes that will not degrade the performance of the non GPU code.

2024-05-07 14:58 UTC, jrbidlot commented on src/ecwam/wamintgr_loki_gpu.F90
is this new routine necessary. It looks like duplication of the existing wamintgr.F90

2024-05-07 15:34 UTC, awnawab commented on src/ecwam/wamintgr_loki_gpu.F90
`wamintgr_loki_gpu.F90` has all the FIELD_API data offload instructions to move data from host to device. We can't auto-generate these at the moment, hence the need to have the duplicated routine. Once we've made more progress with porting the grid-point code in the IFS dycore, we'll finalise the FIELD_API templates and I'll remove this duplicate routine.

2024-05-07 15:39 UTC, awnawab commented on src/ecwam/propag_wam.F90
>                     CALL PROPAGS2(FL1_EXT(:,:,1:IFRELFMAX), FL3_EXT(:,:,1:IFRELFMAX), NINF, NSUP, KIJS, KIJL, NANG, 1, IFRELFMAX)
The current develop branch is up-to-date with 49r1, but of course the wave propagation GPU porting began last year before we had merged in the 49r1 changes. I missed the significant changes because the results were bit-identical. Thanks a lot for the heads up, I'll reapply the GPU port to the 49r1 version of propags2.

2024-05-07 15:42 UTC, awnawab commented on src/ecwam/propags2.F90
> +              IF (LLWKPMN(K,M,-1).AND.(.NOT.LLWKPMN(K,M,1))) THEN
The changes were neutral to CPU performance, but I will have to test this again once I've reapplied the GPU port over 49r1 propags2. At first glance, the FJ1 to FJ5 arrays shouldn't hurt GPU performance, but I'll have to confirm after testing.

2024-05-07 15:44 UTC, awnawab commented on src/ecwam/propag_wam.F90
> -              FL1_EXT(IJSB:IJLB, K, M) = FL1(KIJS:KIJL, K, M, ICHNK)
Great spot! I think we can keep KIJS, shouldn't have any performance impact.

2024-05-08 09:58 UTC, jrbidlot commented on src/ecwam/propag_wam.F90
>                     CALL PROPAGS2(FL1_EXT(:,:,1:IFRELFMAX), FL3_EXT(:,:,1:IFRELFMAX), NINF, NSUP, KIJS, KIJL, NANG, 1, IFRELFMAX)
Ahmad, you have been very good at including us in the PR process.
Do you thing we should include you more in Josh and my work.
Josh is planning new features with his work on wave-sea ice interaction for 50R1.
So, it might be useful to add you the review process...

2024-05-08 09:59 UTC, jrbidlot commented on src/ecwam/propags2.F90
> +              IF (LLWKPMN(K,M,-1).AND.(.NOT.LLWKPMN(K,M,1))) THEN
Did you test it at operational resolution (Tco1279)?

2024-05-08 11:29 UTC, awnawab commented on src/ecwam/propag_wam.F90
>                     CALL PROPAGS2(FL1_EXT(:,:,1:IFRELFMAX), FL3_EXT(:,:,1:IFRELFMAX), NINF, NSUP, KIJS, KIJL, NANG, 1, IFRELFMAX)
Yes please, I think that's a great idea! It will make working around any potential clashes/merge conflicts much more efficient 🙏

2024-05-08 13:28 UTC, jkousal32 commented
It is all pretty new code to me, but looks good! Even if I might not spot any potential issues, it is nice to see the sorts of things necessary for getting ready for running on GPU

2024-05-08 13:36 UTC, jrbidlot commented on src/ecwam/propags2.F90
> +              IF (LLWKPMN(K,M,-1).AND.(.NOT.LLWKPMN(K,M,1))) THEN
Yes, to be sure can you try 01280.

2024-05-08 19:57 UTC, awnawab commented on src/ecwam/propags2.F90
> +              IF (LLWKPMN(K,M,-1).AND.(.NOT.LLWKPMN(K,M,1))) THEN
The wave propagation kernel performance difference on an O1280 grid is also 1%, but this time in the favour of the code in the current PR. I think we can safely conclude the changes are performance neutral on the CPU.

I also ran coupled IFS+nemo tco399 simulations again to test the changes to propags2. The output is still bit-identical.

2024-05-08 21:16 UTC, jrbidlot commented on src/ecwam/propags2.F90
> +              IF (LLWKPMN(K,M,-1).AND.(.NOT.LLWKPMN(K,M,1))) THEN
Good to know. Thank you

2024-05-10 09:05 UTC, wdeconinck approved these changes
Thanks for addressing my suggestions. A few more tiny improvements, but signing off already.

2024-05-10 09:05 UTC, wdeconinck commented on CMakeLists.txt
> +                    REQUIRED_PACKAGES "MPI COMPONENTS Fortran"
```suggestion
```

2024-05-10 09:05 UTC, wdeconinck commented on CMakeLists.txt
> +                    DESCRIPTION "Enable CUDA-aware MPI"
```suggestion
                    DESCRIPTION "Enable GPU-aware MPI" 
```

2024-05-10 13:31 UTC, jrbidlot approved these changes
It looks OK as far as I can tell. 

We are hopefully making good progress towards GPU speed-up.

2024-05-14 06:53 UTC, merged