IFS 49R2 science sync
ecmwf-ifs/ecwam pull request #25
Opened 2024-08-02 14:10 UTC by awnawab

This PR brings over all the scientific developments for the wave model as part of 49R2.

One of the main developments is the ability to output bathymetry files in grib, and this is now the default for etopo grids. When this option is enabled, the `wam_subgrid_?` files are output by `create_bathymetry` rather than by `preproc`. The scripts have been modified to reflect this; if `create_bathymetry` is run then the subgrid files are also cached for reuse just like `wam_topo`. The grib output is therefore disabled for aqua grids because these don't require `create_bathymetry`. We can potentially clean this up in a later PR if there is a case for needing grib output in aqua grids too.

I am filing this as a draft only because I have not updated all of the validation norms, just those needed for the CI. Once this PR is approved, I'll update the remaining validation norms.

Once merged, could this please be tagged as 1.4.0?

2024-08-02 14:13 UTC, awnawab commented
@jrbidlot and @jkousal32 could you also please review this PR? Thanks!

2024-08-06 12:17 UTC, wdeconinck reviewed
Generally good to me. Thanks! And please check my question below.

2024-08-06 12:17 UTC, wdeconinck commented on share/ecwam/scripts/ecwam_run_preproc.sh
> +
In principle this export could be applied to all platforms, and can go into the ecwam_runtime instead.

2024-08-06 12:17 UTC, wdeconinck commented on share/ecwam/scripts/ecwam_run_model.sh
> +lgribout=T
Hi @jrbidlot does this variable in the namelist affect the restart file output only?
Does this mean that the restarts are not preserving all bits anymore so that restarting is no longer bit-identical?

2024-08-06 14:05 UTC, jrbidlot commented on share/ecwam/scripts/ecwam_run_model.sh
> +lgribout=T
This is correct. Writing out the restart file in gtib will not allow to have a restart that is bit identical.
We do it all the time when running under prepIFS because the restart files are then fetch with mars (hence in grib).
For the standalone testing, I don't think we actually continue a run from restart produced by a previous run but we need to assume that if users were to try to do this, they would restart from pure binary restart because they would not want to handle grib restart like we do ec ECMWF because it implies coding wave spectra in grib which no one does but ECMWF. So keep lgribout=F

2024-08-07 16:39 UTC, cxzk requested changes
This generally looks consistent with my preliminary squashed merge that I've been using for testing (and indeed most differences from that are either in parts I didn't need to update for my purposes, or due to my own mis-merging.)

However, there are a couple of things that should be fixed - one is a (harmless) duplicate block of code that's been introduced in `OUT_ONEGRDPT`; the other is an apparent mis-merge in `WGRIB_ENCODE` that results in some spectral outputs not having `direction` and `frequency` set correctly - in particular this affects the bathymetry files generated by the IFS `wconst` task, which leads to a crash when the model tries to read them in.

Once that is fixed, this does seem to be bit-identical to my previous testing when run in the context of the full IFS continuous integration suite.

2024-08-20 11:49 UTC, awnawab commented on src/ecwam/out_onegrdpt.F90
> +
Well spotted, thanks!

2024-08-20 11:49 UTC, awnawab commented on src/ecwam/wgribencode.F90
>        IF (IPARAM == 251) THEN
Thanks a lot for testing and finding this mis-merge 🙏

2024-08-20 11:50 UTC, awnawab commented
Many thanks all for your reviews and feedback 🙏 I've applied all of the fixes you suggested. I'll now update the remaining validation norms.

2024-08-20 13:06 UTC, jrbidlot approved these changes
As far as I can see this now inline with what went in 49R2.

2024-08-27 11:31 UTC, cxzk commented
> Many thanks all for your reviews and feedback 🙏 I've applied all of the fixes you suggested. I'll now update the remaining validation norms.

Thanks - the updated branch now passes all my testing for IFS CY50R1.

2024-08-27 11:32 UTC, cxzk approved these changes

2024-08-28 09:28 UTC, awnawab commented
Thanks again for the feedback all. I've now updated all the validation hashes, and I've also included a bug fix contributed by @jrbidlot offline.

2024-09-03 14:14 UTC, wdeconinck approved these changes
Looks great! Thanks!

2024-09-03 14:38 UTC, merged