adapt CMakeLists.txt to latest multio-fapi
ecmwf-ifs/ecwam pull request #28
Opened 2024-09-09 16:17 UTC by cxzk

This cross-ports a fix from IFS CY49R1 that was missing and its absence here was causing MULTIO configuration to fail in the standalone WAM experiment in the IFS develop CI.

* adapt CMakeLists.txt to latest multio-fapi

2024-09-10 09:23 UTC, cresswellp approved these changes
Strictly speaking, I'm not sure if both `HAVE_MULTIO` and `multio_FOUND` are necessary - this is internal ecBuild logic, but I suspect the former implies the latter.

@wdeconinck please can you advise - is the code here 'correct' or can it be simplified?

2024-09-10 09:41 UTC, awnawab requested changes
Many thanks for porting this over @cxzk! It looks sensible to me, I've left two small comments, the more important one being the version check as this will trigger a more easily debuggable configure time failure if we are using the wrong multio.

I'd also like to highlight that `develop-1.3` is a branch mainly targeted at GPU related developments on top of 49R1, one of which is not bitid.

Do you need this fix in a tag that is bitid to 49R1? If so, this should go in before #27 and should be tagged before that is merged.

2024-09-10 09:41 UTC, awnawab commented on src/ecwam/CMakeLists.txt
> +  if(multio_FOUND)
This is indeed superfluous, as we are already checking for `HAVE_MULTIO`.

2024-09-10 09:41 UTC, awnawab commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES multio-fapi)
Since the name of the library has changed, this would be a non backwards-compatible change that corresponds to a new multio release. Could we please add a multio version check as part of the`MULTIO` option?

2024-09-10 10:04 UTC, cxzk commented
> Do you need this fix in a tag that is bitid to 49R1? If so, this should go in before #27 and should be tagged before that is merged.

Yes, that is required in order to be able to get the standalone WAM CI test running as part of the IFS "develop" CI, as "develop" is only intended to take bit-identical changes relative to the current cycle - that's why I targeted it at develop-1.3 rather than develop.

2024-09-10 10:07 UTC, cxzk commented on src/ecwam/CMakeLists.txt
> +  if(multio_FOUND)
No problem, I'll remove this extra check that was added in IFS CY49R1, if it's not actually required.

2024-09-10 10:08 UTC, cxzk commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES multio-fapi)
I'm not clear exactly what is required here to do that, but if you can advise then I'm happy to add this.

2024-09-10 11:13 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +  if(multio_FOUND)
Agreed, multio_FOUND is not needed

2024-09-10 11:36 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES multio-fapi)
Does this change depend on the version of multio?

2024-09-10 11:59 UTC, dsarmany commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES -Wl,--push-state,--no-as-needed multio-fapi -Wl,--pop-state)
I don't think `--no-as-needed` is necessary when linking to `multio-fapi`.

2024-09-10 12:19 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES multio-fapi)
This is tangential to this PR, but the static linking version
```bash
-Wl,--push-state,--no-as-needed multio-fdb5 -Wl,--pop-state
```
 is dated from 2017, and I think in the mean time we don't need this anymore because multio-fdb5 (at least from version 2.1 is always compiled as shared library.

Perhaps it is sufficient to just keep
```cmake
list(APPEND MULTIO_LIBRARIES multio-fapi)
```
So that means we must require multio VERSION 2.1

2024-09-10 13:32 UTC, awnawab commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES multio-fapi)
It would be good to wrap up all the multio related cmake changes here if possible.

2024-09-11 08:51 UTC, cxzk commented on src/ecwam/CMakeLists.txt
> +  if(multio_FOUND)
Removed in latest push.

2024-09-11 08:52 UTC, cxzk commented on src/ecwam/CMakeLists.txt
> +        list(APPEND MULTIO_LIBRARIES multio-fapi)
Special static linking rule removed, and required version updated, as suggested, in latest push.

2024-09-11 08:53 UTC, cxzk commented
All comments hopefully addressed in latest push, which I can confirm is still working in the IFS context I was trying to fix.

2024-09-11 09:00 UTC, awnawab approved these changes
Many thanks @cxzk for addressing the comments, good to go now as far as I can tell 👍

2024-09-11 11:13 UTC, wdeconinck approved these changes
Thanks @cxzk for addressing all suggestions!

2024-09-11 11:13 UTC, merged