Naan port wamodel
ecmwf-ifs/ecwam pull request #34
Opened 2024-10-08 08:21 UTC by awnawab

2024-10-08 13:06 UTC, awnawab commented
@jksoual32 and @jrbidlot, could you please also review this PR? Many thanks!

2024-10-08 14:03 UTC, jrbidlot commented
Ahmad,
silly question. Changing outblock affects the output, many of those are pure diagnostic parameters.
Have you checked that the output file id the same in both cases?

2024-10-08 14:18 UTC, awnawab commented
> Ahmad, silly question. Changing outblock affects the output, many of those are pure diagnostic parameters. Have you checked that the output file id the same in both cases?

The validation passes both on CPU and GPU after these changes, so I am reasonably confident I haven't changed the results. But of course I will double check and run checksums on the output file before and after this change.

Just to be sure, the relevant file to check would be the path stored in `CNORMWAMOUT_FILE` right?

2024-10-09 10:43 UTC, awnawab commented
> Ahmad, silly question. Changing outblock affects the output, many of those are pure diagnostic parameters. Have you checked that the output file id the same in both cases?

Just confirmed (using sha256sum) that the contents of `CNORMWAMOUT_FILE` are identical on CPU before and after this PR. On GPU they are not, but that is expected because as this PR runs more of ecWAM on device, we will get small round-off differences.

2024-10-09 12:44 UTC, jkousal32 approved these changes
looks okay to me!

2024-10-10 09:19 UTC, jrbidlot requested changes
Hi Ahmad,
I think there is a bug in outblock around old line 555

The tricky bit with outblock is that it produces many purely diagnostic output and so it would not be picked-up by checking the standard output norms.

Did you test with all possible output turned on?

2024-10-11 06:47 UTC, awnawab commented on src/ecwam/outblock.F90
> +        IF (IPFGTBL(59) /= 0) THEN
Excellent catch! There was another similar loop over `NTRAIN` earlier that I also missed. I've now fixed it and confirmed that the norms are identical even if all 87 output parameters are enabled. Many thanks for spotting this 🙏

2024-10-14 04:03 UTC, mlange05 approved these changes
Looks good to me.

2024-10-28 10:16 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> -    PRIVATE_DEFINITIONS ${ECWAM_PRIVATE_DEFINITIONS}
The underscore in _CUDA gives the impression it is defined by the compiler. Probably it is better to use a WAM_HAVE_CUDA definition as for some other defines.

2024-10-30 16:25 UTC, awnawab commented
Many thanks @wdeconinck for spotting that, it is indeed more intuitive to rename the preproc def as you suggest. As discussed offline, if you are happy with the fix, could you please merge the branch? I will address the failing macos CI tests in a follow up PR.

2024-10-31 08:50 UTC, merged