Add default compiler flags for Cray
ecmwf-ifs/ecwam pull request #47
Opened 2024-12-10 21:45 UTC by ioanhadade

Add compiler flags -ram -emf -hflex_mp=conservative -Othread1 -hfp1 -hadd_paren to prevent random SIGFPEs

2024-12-11 14:40 UTC, awnawab requested changes
Thanks a lot @ioanhadade for filing this fix 🙏  just a small nitpicky comment that would help clarify what some of these flags are for.

2024-12-11 14:40 UTC, awnawab commented on cmake/ecwam_compile_flags.cmake
> +  set(general_flags       "-ram -emf -hflex_mp=conservative -Othread1 -hfp1 -hadd_paren" )
At the time I was suggesting a quick fix, but I think we can split up these flags into more descriptive categories. So possibly something like this:

```
set(threading_flags "-hflex_mp=conservative -Othread1")
set(fpmodel_flags "-hfp1 -hadd_paren")
set(baseline_flags "-ram -emf")
```

2024-12-18 08:08 UTC, awnawab approved these changes
Thanks a lot @ioanhadade for addressing the comment 🙏 one optional nitpick is to remove the setting of `general_flags` which no longer exist, but I can also mop this up in a future PR.

2024-12-18 08:09 UTC, ioanhadade commented
> Thanks a lot @ioanhadade for addressing the comment 🙏 one optional nitpick is to remove the setting of `general_flags` which no longer exist, but I can also mop this up in a future PR.

I can do it now. One sec.

2024-12-18 14:16 UTC, merged