ifs-source sync
ecmwf-ifs/ecwam pull request #8
Opened 2023-12-28 21:48 UTC by awnawab

This PR is one part of a two-way sync between ifs-source contrib/ecwam and the standalone repo. The corresponding ifs-source branch is:
https://git.ecmwf.int/users/naan/repos/ifs-source/commits?until=refs%2Fheads%2Fnaan_CY49R1_ecwam_sync.IFS-3196

The code herein is string identical to the ifs-source branch, which has bit-identical results in both double and single precision to the CY49R1 CI forecast experiment.

The PR comprises mostly of the scientific changes for CY49. The validation hashes for all the test cases are updated accordingly. Some technical changes are also included:
- Updated runner scripts to reflect the updated namelist inputs in CY49
- Fix to the FIELD_API fetchcontent mechanism to pick up FIELD_API in ifs-source/contrib
- LUMI-G communication hang fix contributed by Ioan Hadade
- NVHPC optimization downgrade for sbottom.F90 contributed by Michael Lange

2023-12-28 21:49 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ecwam?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ecwam?pullRequest=8) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: wdeconinck<br/>:white_check_mark: awnawab<br/>:x: jrbidlot<br/>:x: ioanhadade<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/ecwam?pullRequest=8) it.</sub>

2023-12-29 09:21 UTC, awnawab commented
@ioanhadade and @jrbidlot could you please sign the CLA? This PR contains commits contributed by both of you. @jrbidlot as most of the commits included herein are yours, could you also please review the PR? Thanks!

2024-01-08 13:57 UTC, wdeconinck requested changes

2024-01-08 13:57 UTC, wdeconinck commented on CMakeLists.txt
> +
This could be replaced with
```
ecbuild_add_option( FEATURE ECFLOW
                    DESCRIPTION "ecflow meter updates"
                    REQUIRED_PACKAGES )
```
It is then not an absolutely required package unless requested via "-DENABLE_ECFLOW=ON" or in the bundle.yml.
This then does not bind this feature to a package or bundle name.

2024-01-08 13:57 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +    PUBLIC_LIBS      fiat parkind_${prec} $<$<NOT:${ECWAM_STANDALONE}>:ecflow_lightf> ${ecwam}_intfb
```suggestion
    PUBLIC_LIBS      fiat parkind_${prec} $<${HAVE_ECFLOW}:ecflow_lightf> ${ecwam}_intfb
```

2024-01-08 13:57 UTC, wdeconinck commented on src/ecwam/CMakeLists.txt
> +    PUBLIC_DEFINITIONS ${ECWAM_DEFINITIONS} $<${ECWAM_STANDALONE}:_ECWAM_STANDALONE>
Can the logic of `_ECWAM_STANDALONE` be changed to PRIVATELY define variable `WAM_HAVE_ECFLOW`
and use that within the code?
This is consistent with other  preprocessor definitions.

2024-01-08 14:53 UTC, ioanhadade commented
done
________________________________
From: Ahmad Nawab ***@***.***>
Sent: 29 December 2023 10:21
To: ecmwf-ifs/ecwam ***@***.***>
Cc: Ioan Hadade ***@***.***>; Mention ***@***.***>
Subject: Re: [ecmwf-ifs/ecwam] ifs-source sync (PR #8)


@ioanhadade<https://github.com/ioanhadade> and @jrbidlot<https://github.com/jrbidlot> could you please sign the CLA? This PR contains commits contributed by both of you. @jrbidlot<https://github.com/jrbidlot> as most of the commits included herein are yours, could you also please review the PR? Thanks!

—
Reply to this email directly, view it on GitHub<https://github.com/ecmwf-ifs/ecwam/pull/8#issuecomment-1871868729>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AI7K3UTJ5GNZAXXAGV2MVX3YL2DS7AVCNFSM6AAAAABBF5XTEGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZRHA3DQNZSHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-01-25 11:47 UTC, merged